version: '3.10'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-app
    image: hannahan2/web-app:latest
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    restart: always