version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017