name: CI / CD
on: [pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Images with Docker Compose
        run: docker-compose build

      - name: Run Tests
        run: |
          docker-compose up -d
          docker-compose exec web pytest
          docker-compose down
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images
        run: |
          docker-compose push